baseURL: http://www.example.com
title: Wilson Freitas
theme: "hugo-coder"
languageCode: pt-br
defaultContentLanguage: pt-br
paginate: 20
enableEmoji: yes
params:
  author: Wilson Freitas
  avatarURL: "images/Foto Perfil do Instagram 2.png"
  colorScheme: auto
  commit: https://github.com/luizdepra/hugo-coder/tree/
  # csp:
  #   childsrc: '''self'''
  #   connectsrc:
  #     - '''self'''
  #     - https://www.google-analytics.com
  #   fontsrc:
  #     - '''self'''
  #     - https://fonts.gstatic.com
  #     - https://cdn.jsdelivr.net/
  #   formaction: '''self'''
  #   framesrc: '''self'''
  #   imgsrc: '''self'''
  #   objectsrc: '''none'''
  #   prefetchsrc: '''self'''
  #   scriptsrc:
  #     - '''self'''
  #     - '''unsafe-inline'''
  #     - https://www.google-analytics.com
  #   stylesrc:
  #     - '''self'''
  #     - '''unsafe-inline'''
  #     - https://fonts.googleapis.com/
  #     - https://cdn.jsdelivr.net/
  customCSS:
    - css/custom.css
  customJS: []
  customSCSS: []
  dateFormat: 2006-01-02
  description: Wilson Freitas
  hideColorSchemeToggle: no
  info:
    - Quant
    - Professor
  keywords: blog,desenvolvedor,quant,pessoal
  maxSeeAlsoItems: 5
  rtl: no
  since: 2022
  social:
    - icon: fa fa-2x fa-github
      name: Github
      url: https://github.com/wilsonfreitas/
      weight: 1
    - icon: fa fa-2x fa-twitter
      name: Twitter
      url: https://twitter.com/aboutwilson/
      weight: 3
    - icon: fa fa-2x fa-linkedin
      name: LinkedIn
      url: https://www.linkedin.com/in/wilson-freitas/
      weight: 4
    - icon: fa fa-2x fa-medium
      name: Medium
      url: https://medium.com/@wilsonfreitas
      weight: 5
    - icon: fa fa-2x fa-rss
      name: RSS
      rel: alternate
      type: application/rss+xml
      url: https://myhugosite.com/index.xml
      weight: 6
taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
languages:
  pt-br:
    languageName: ':brazil:'
    menu:
      main:
        - name: Sobre
          url: about/
          weight: 1
        - name: Blog
          url: posts/
          weight: 2
        - name: Projetos
          url: projects/
          weight: 3
    params:
      author: Wilson Freitas
      description: A realidade insiste em me arruinar
      info: Quant e Professor
      keywords: blog,desenvolvedor,quant,pessoal
    title: Wilson Freitas
